@startuml

package レシピ {
    class レシピ {
        ID
        タイトル
    }
}

package 材料 {
    class 材料 {
    }
}


package 材料カテゴリ {
    class 材料カテゴリ {
        ID
        タイトル
    }

    class 材料要素 {
        名称
        分量
    }

    材料カテゴリ o--"0..100" 材料要素
}

package 作り方 {
    class 作り方 {
    }
}

package 手順 {
    class 手順 {
        ID
        内容
    }
}

レシピ <-- "1" 材料
レシピ <-- "1" 作り方

材料 --> 材料カテゴリ : "0..10（ID だけを持つ）" 
作り方 --> 手順 : "0..100（ID だけを持つ）"

@enduml
