@startuml

class レシピ {
    ID
    タイトル
}

class 材料 {
}

class 材料カテゴリ {
    ID
    タイトル
}

class 材料要素 {
    ID
    名称
    分量
}

class 作り方 {
}

class 手順 {
    ID
    内容
}

レシピ o-- "1" 材料
材料 o-- "0..10" 材料カテゴリ
材料カテゴリ o--"0..100" 材料要素

レシピ o-- "1" 作り方
作り方 o-- "0..100" 手順

@enduml
