@startuml
left to right direction

actor 利用者

利用者 --> (レシピを作成する)
利用者 --> (材料を変更する)
利用者 --> (作り方を変更する)
利用者 --> (レシピを削除する)

(材料を変更する) --> (材料カテゴリを追加する)
(材料を変更する) --> (材料カテゴリを変更する)
(材料を変更する) --> (材料カテゴリを並び替える)
(材料を変更する) --> (材料カテゴリを削除する)
(作り方を変更する) --> (手順を追加する)
(作り方を変更する) --> (手順を変更する)
(作り方を変更する) --> (手順を並び替える)
(作り方を変更する) --> (手順を削除する)

note right of (レシピを作成する)
最初タイトルだけ入力して登録する
end note
@enduml
